baseURL = "https://example.com/"
title = "Sadra Blog"
languageCode = "fa-IR"
defaultContentLanguage = "fa"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

summaryLength = 0
disableKinds = ["RSS", "sitemap", "taxonomy", "taxonomyTerm"]

[params]
  env = "production"
  title = "Sadra Blog"
  description = "وبلاگ سدره علی‌آبادی"
  keywords = ["Blog", "Hugo", "PaperMod"]
  author = "Sadra Aliabadi"
  defaultTheme = "light"
  disableThemeToggle = false

  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = false
  disableSpecial1stPost = true
  disableScrollToTop = true
  comments = false
  hidemeta = true
  hideSummary = true
  showtoc = false
  tocopen = false

  [params.cover]
    hidden = true
    hiddenInList = true
    hiddenInSingle = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[frontmatter]
  summary = [""]

[permalinks]
  blog = "/:slug/"

[minify]
  disableXML = true
  minifyOutput = true

[pagination]
  pagerSize = 5

[params.assets]
  customCSS = ["/css/rtl.css"]

[menu]

  [[menu.main]]
    identifier = "categories"
    name = "دسته‌بندی‌ها"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "برچسب‌ها"
    url = "/tags/"
    weight = 20